title: Algoritmos e ProgramaÃ§Ã£o I ğŸ‘©â€ğŸ’».
description: Materiais da disciplina de Algoritmos e ProgramaÃ§Ã£o de Computadores I.
show_downloads: false
google_analytics:
remote_theme: Gabriel-Sousa-Amorim/Serenity-Theme
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
